// <auto-generated />
using System;
using AMMCrawler;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AMMCrawler.Migrations
{
    [DbContext(typeof(CrawlerContext))]
    partial class CrawlerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("AMMCrawler.Entities.ResourceCrawlMapping", b =>
                {
                    b.Property<int>("FoundLinkID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CrawledLinkID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FoundLinkID1")
                        .HasColumnType("INTEGER");

                    b.HasKey("FoundLinkID", "CrawledLinkID");

                    b.HasIndex("FoundLinkID1");

                    b.ToTable("ResourceMappings");
                });

            modelBuilder.Entity("AMMCrawler.Entities.ResourceLink", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCrawled")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("URL")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("ResourceLinks");
                });

            modelBuilder.Entity("AMMCrawler.Entities.ResourceCrawlMapping", b =>
                {
                    b.HasOne("AMMCrawler.Entities.ResourceLink", "CrawledLink")
                        .WithMany("Crawls")
                        .HasForeignKey("FoundLinkID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AMMCrawler.Entities.ResourceLink", "FoundLink")
                        .WithMany()
                        .HasForeignKey("FoundLinkID1");

                    b.Navigation("CrawledLink");

                    b.Navigation("FoundLink");
                });

            modelBuilder.Entity("AMMCrawler.Entities.ResourceLink", b =>
                {
                    b.Navigation("Crawls");
                });
#pragma warning restore 612, 618
        }
    }
}
