// <auto-generated />
using System;
using AMMCrawler.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AMMCrawler.DAL.Migrations
{
    [DbContext(typeof(CrawlerContext))]
    [Migration("20210404093949_ApplicationInfo")]
    partial class ApplicationInfo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("AMMCrawler.DAL.Entities.Application", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("RootURL")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("AMMCrawler.DAL.Entities.CrawlRunInfo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApplicationID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("End")
                        .HasColumnType("TEXT");

                    b.Property<int>("EtcCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InnerCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OuterCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Start")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("ApplicationID");

                    b.ToTable("RunInfo");
                });

            modelBuilder.Entity("AMMCrawler.DAL.Entities.ETCLinkMetadata", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInternal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ResourceLinkID")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("ResourceLinkID");

                    b.ToTable("ETCLinksMetadata");
                });

            modelBuilder.Entity("AMMCrawler.DAL.Entities.ResourceCrawlMapping", b =>
                {
                    b.Property<int>("FoundLinkID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CrawledLinkID")
                        .HasColumnType("INTEGER");

                    b.HasKey("FoundLinkID", "CrawledLinkID");

                    b.HasIndex("CrawledLinkID");

                    b.ToTable("ResourceMappings");
                });

            modelBuilder.Entity("AMMCrawler.DAL.Entities.ResourceLink", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApplicationID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCrawled")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("URL")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("ApplicationID");

                    b.ToTable("ResourceLinks");
                });

            modelBuilder.Entity("AMMCrawler.DAL.Entities.CrawlRunInfo", b =>
                {
                    b.HasOne("AMMCrawler.DAL.Entities.Application", "Application")
                        .WithMany()
                        .HasForeignKey("ApplicationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("AMMCrawler.DAL.Entities.ETCLinkMetadata", b =>
                {
                    b.HasOne("AMMCrawler.DAL.Entities.ResourceLink", "ResourceLink")
                        .WithMany()
                        .HasForeignKey("ResourceLinkID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResourceLink");
                });

            modelBuilder.Entity("AMMCrawler.DAL.Entities.ResourceCrawlMapping", b =>
                {
                    b.HasOne("AMMCrawler.DAL.Entities.ResourceLink", "CrawledLink")
                        .WithMany("Crawls")
                        .HasForeignKey("CrawledLinkID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AMMCrawler.DAL.Entities.ResourceLink", "FoundLink")
                        .WithMany()
                        .HasForeignKey("FoundLinkID");

                    b.Navigation("CrawledLink");

                    b.Navigation("FoundLink");
                });

            modelBuilder.Entity("AMMCrawler.DAL.Entities.ResourceLink", b =>
                {
                    b.HasOne("AMMCrawler.DAL.Entities.Application", "Application")
                        .WithMany()
                        .HasForeignKey("ApplicationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("AMMCrawler.DAL.Entities.ResourceLink", b =>
                {
                    b.Navigation("Crawls");
                });
#pragma warning restore 612, 618
        }
    }
}
